active_stack_name: local_stack
stack_components:
  artifact_store:
    local_artifact_store: local
  metadata_store:
    local_metadata_store: sqlite
  orchestrator:
    local_orchestrator: local
stacks:
  local_stack:
    artifact_store: local_artifact_store
    container_registry: null
    metadata_store: local_metadata_store
    orchestrator: local_orchestrator
    step_operator: null
version: 0.6.3
